import { ArrowRight, BarChart3, Code, GraduationCap } from 'lucide-react';

export default function Hero() {
  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section id="home" className="pt-24 pb-16 bg-gradient-to-br from-slate-50 via-emerald-50/30 to-slate-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="space-y-8">
            <div className="inline-flex items-center space-x-2 bg-emerald-100 text-emerald-700 px-4 py-2 rounded-full text-sm font-medium">
              <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse"></span>
              <span>Learn. Trade. Profit.</span>
            </div>

            <h1 className="text-5xl md:text-6xl font-bold text-slate-900 leading-tight">
              Master Trading with
              <span className="text-emerald-600"> Expert Guidance</span>
            </h1>

            <p className="text-xl text-slate-600 leading-relaxed">
              From candlestick basics to advanced algorithmic trading. Learn proven strategies
              and access high-performing trading bots that generate consistent profits.
            </p>

            <div className="flex flex-col sm:flex-row gap-4">
              <button
                onClick={() => scrollToSection('courses')}
                className="group bg-emerald-600 text-white px-8 py-4 rounded-lg hover:bg-emerald-700 transition-all flex items-center justify-center space-x-2 shadow-lg hover:shadow-xl"
              >
                <span className="font-semibold">Explore Courses</span>
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </button>
              <button
                onClick={() => scrollToSection('scripts')}
                className="bg-white text-slate-700 px-8 py-4 rounded-lg hover:bg-slate-50 transition-all border-2 border-slate-200 font-semibold"
              >
                View Trading Bots
              </button>
            </div>

            <div className="grid grid-cols-3 gap-6 pt-8 border-t border-slate-200">
              <div>
                <div className="text-3xl font-bold text-emerald-600">10K+</div>
                <div className="text-sm text-slate-600">Active Students</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-emerald-600">50+</div>
                <div className="text-sm text-slate-600">Trading Bots</div>
              </div>
              <div>
                <div className="text-3xl font-bold text-emerald-600">95%</div>
                <div className="text-sm text-slate-600">Success Rate</div>
              </div>
            </div>
          </div>

          <div className="relative">
            <div className="grid grid-cols-2 gap-6">
              <div className="space-y-6">
                <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow border border-slate-100">
                  <GraduationCap className="w-12 h-12 text-emerald-600 mb-4" />
                  <h3 className="text-lg font-semibold text-slate-900 mb-2">Expert Courses</h3>
                  <p className="text-slate-600 text-sm">Learn from industry professionals with proven track records</p>
                </div>
                <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow border border-slate-100">
                  <BarChart3 className="w-12 h-12 text-emerald-600 mb-4" />
                  <h3 className="text-lg font-semibold text-slate-900 mb-2">Proven Results</h3>
                  <p className="text-slate-600 text-sm">Access bots with verified performance metrics</p>
                </div>
              </div>
              <div className="space-y-6 pt-12">
                <div className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow border border-slate-100">
                  <Code className="w-12 h-12 text-emerald-600 mb-4" />
                  <h3 className="text-lg font-semibold text-slate-900 mb-2">Algo Trading</h3>
                  <p className="text-slate-600 text-sm">Build and deploy automated trading systems</p>
                </div>
                <div className="bg-gradient-to-br from-emerald-600 to-emerald-700 p-6 rounded-xl shadow-lg text-white">
                  <div className="text-3xl font-bold mb-2">$2.4M+</div>
                  <p className="text-emerald-100">Total Profits Generated by Our Community</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
